config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, only: [:new, :create, :index]

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, uniqueness: true, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up or Sign In", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>List of Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <span><h3>Title: </span><%= post.title%></h3>
    </li>
    <li>
      <span>Body: </span><%= post.body%>
    </li>
    <% if user_signed_in? %>
      <li>
        <span>Author: </span><%= post.user.name%>
    </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Create New Post", new_post_path %> <br>

app/views/posts/new.html.erb
  <%= form_with model: @post do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.label :title, "Title" %> <br/>
    <%= form.text_field :title, placeholder: "Enter your title"  %> <br/>
    <%= form.label :body, "Body" %> <br/>
    <%= form.text_field :body, placeholder: "Enter your post content " %> <br/>
    <%= form.submit "Submit this form" %>
  <% end %>